export const themeArtifacts = [
  {
    id: 'evergreen',
    name: 'Evergreen',
    storyName: 'Evergreen',
    sectionTitle: 'Evergreen Theme',
    eyebrow: 'Theme color palette',
    title: 'Evergreen theme with warm complementary accents.',
    description:
      'This five-color website palette uses #00274f as the anchor, then balances it with a softer supporting blue, a muted red, a refined gold, and a practical neutral grey for interface depth and content structure.',
    heroClassName: '',
    previewClassName: '',
    eyebrowColor: 'var(--theme-color-secondary)',
    accentChip: {
      label: 'Gold Accent',
      background: 'var(--theme-color-gold)',
      color: 'var(--theme-color-primary)',
    },
    previewTitle: 'Brand-ready website colors',
    previewDescription:
      'Strong contrast for navigation and headers, with warmer accents for calls to action, badges, and featured content.',
    actions: [
      { label: 'Primary Action', className: 'button-primary' },
      { label: 'Secondary Link', className: 'button-secondary' },
    ],
    colors: {
      primary: '#00274f',
      secondary: '#335a7a',
      gold: '#d6b25e',
      red: '#a84a4a',
      grey: '#8a949f',
      sage: '#6f8f3a',
      terracotta: '#c97a52',
      mist: '#d8e7f2',
      stone: '#c6ccd4',
      cloud: '#edf1f5',
      paper: '#f6f8fb',
      ink: '#0f1720',
      shadow: '0 18px 50px rgba(0, 39, 79, 0.12)',
      heroStart: 'rgba(0, 39, 79, 0.98)',
      heroEnd: 'rgba(51, 90, 122, 0.96)',
      glow: 'rgba(214, 178, 94, 0.24)',
    },
    swatches: [
      {
        name: 'Primary Navy',
        role: 'Headers, navigation, footer, key brand moments',
        hex: '#00274F',
        oklch: 'oklch(24.67% 0.082 257.14)',
        color: 'var(--theme-color-primary)',
      },
      {
        name: 'Supporting Blue',
        role: 'Secondary panels, hover states, data/UI accents',
        hex: '#335A7A',
        oklch: 'oklch(45.31% 0.065 250.92)',
        color: 'var(--theme-color-secondary)',
      },
      {
        name: 'Gold Accent',
        role: 'Primary CTAs, highlight bars, premium details',
        hex: '#D6B25E',
        oklch: 'oklch(77.62% 0.106 85.46)',
        color: 'var(--theme-color-gold)',
      },
      {
        name: 'Muted Red',
        role: 'Alerts, editorial emphasis, warm contrast moments',
        hex: '#A84A4A',
        oklch: 'oklch(54.69% 0.142 27.12)',
        color: 'var(--theme-color-red)',
      },
      {
        name: 'Interface Grey',
        role: 'Borders, secondary text, form surfaces, dividers',
        hex: '#8A949F',
        oklch: 'oklch(66.43% 0.022 252.84)',
        color: 'var(--theme-color-grey)',
      },
      {
        name: 'Sage Accent',
        role: 'Status chips, metadata highlights, supporting badges, filter accents',
        hex: '#6F8F3A',
        oklch: 'oklch(60.69% 0.119 126.96)',
        color: 'var(--theme-color-sage)',
      },
      {
        name: 'Terracotta Accent',
        role: 'Pull quotes, editorial callouts, warm hover moments, secondary emphasis',
        hex: '#C97A52',
        oklch: 'oklch(65.60% 0.113 46.96)',
        color: 'var(--theme-color-terracotta)',
      },
      {
        name: 'Mist Blue',
        role: 'Soft content panels, table backgrounds, subtle highlights, reading surfaces',
        hex: '#D8E7F2',
        oklch: 'oklch(92.00% 0.022 239.44)',
        color: 'var(--theme-color-mist)',
      },
      {
        name: 'Stone Neutral',
        role: 'Input borders, card dividers, muted chrome, supporting layout rhythm',
        hex: '#C6CCD4',
        oklch: 'oklch(84.29% 0.013 255.52)',
        color: 'var(--theme-color-stone)',
      },
      {
        name: 'Cloud Neutral',
        role: 'Page wells, large canvas fills, quiet sections, low-noise interface space',
        hex: '#EDF1F5',
        oklch: 'oklch(95.63% 0.007 247.90)',
        color: 'var(--theme-color-cloud)',
      },
    ],
    usageHeading: 'Suggested Website Usage',
    usageItems: [
      ['Primary Navy', 'Use for the global shell, navigation, hero headings, and strong brand blocks.'],
      ['Supporting Blue', 'Use for secondary surfaces, hovers, info cards, and softer navigation states.'],
      ['Gold Accent', 'Use sparingly for CTA buttons, featured content labels, and trust indicators.'],
      ['Muted Red', 'Use for alerts, featured highlights, editorial emphasis, or contrasting badges.'],
      ['Interface Grey', 'Use for neutral UI structure such as outlines, muted copy, and background layers.'],
    ],
  },
  {
    id: 'judiciary',
    name: 'Judiciary',
    storyName: 'Judiciary',
    sectionTitle: 'Judiciary Theme',
    eyebrow: 'Theme color palette',
    title: 'Judiciary theme with brighter supporting accents.',
    description:
      'This alternate five-color website palette keeps #00274f as the structural anchor, then pairs it with #fb4c42, a baby blue, a supporting steel blue, and a mid grey for a cleaner and more modern interface direction.',
    heroClassName: 'theme-artifact-hero--hybrid',
    previewClassName: 'theme-artifact-preview--hybrid',
    eyebrowColor: 'var(--theme-color-coral)',
    accentChip: {
      label: 'Hybrid Accent',
      background: 'var(--theme-color-baby-blue)',
      color: 'var(--theme-color-primary)',
    },
    previewTitle: 'Calm structure, stronger interaction color',
    previewDescription:
      'A dependable website palette for content-heavy layouts and marketing surfaces, with brighter accents reserved for action and emphasis.',
    actions: [
      {
        label: 'Get Started',
        className: 'button-primary',
        style: 'background: var(--theme-color-coral); color: white;',
      },
      { label: 'See Details', className: 'button-secondary' },
    ],
    colors: {
      primary: '#00274f',
      coral: '#fb4c42',
      'baby-blue': '#b9dcff',
      'steel-blue': '#5f8fbe',
      grey: '#8d98a5',
      peach: '#ff9b7a',
      sky: '#8fd3ff',
      lilac: '#d4c1ff',
      graphite: '#667281',
      pearl: '#eef2f7',
      paper: '#f6f8fb',
      ink: '#0f1720',
      shadow: '0 18px 50px rgba(0, 39, 79, 0.16)',
      heroStart: 'rgba(0, 39, 79, 0.98)',
      heroEnd: 'rgba(95, 143, 190, 0.94)',
      glow: 'rgba(251, 76, 66, 0.18)',
    },
    swatches: [
      {
        name: 'Primary Navy',
        role: 'Navigation, headings, layout shell, footer, structural brand moments',
        hex: '#00274F',
        oklch: 'oklch(24.67% 0.082 257.14)',
        color: 'var(--theme-color-primary)',
      },
      {
        name: 'Coral Accent',
        role: 'Primary buttons, alerts, highlight actions, featured emphasis',
        hex: '#FB4C42',
        oklch: 'oklch(67.09% 0.212 29.34)',
        color: 'var(--theme-color-coral)',
      },
      {
        name: 'Baby Blue',
        role: 'Soft surfaces, information panels, highlight backgrounds, airy support color',
        hex: '#B9DCFF',
        oklch: 'oklch(89.08% 0.050 245.31)',
        color: 'var(--theme-color-baby-blue)',
      },
      {
        name: 'Steel Blue',
        role: 'Secondary actions, hover states, sub-navigation, iconography, data accents',
        hex: '#5F8FBE',
        oklch: 'oklch(64.40% 0.087 250.68)',
        color: 'var(--theme-color-steel-blue)',
      },
      {
        name: 'Mid Grey',
        role: 'Borders, muted text, dividers, form surfaces, neutral UI support',
        hex: '#8D98A5',
        oklch: 'oklch(68.04% 0.017 255.84)',
        color: 'var(--theme-color-grey)',
      },
      {
        name: 'Peach Accent',
        role: 'Secondary promotions, onboarding cues, lightweight highlights, warm supporting emphasis',
        hex: '#FF9B7A',
        oklch: 'oklch(78.54% 0.129 39.00)',
        color: 'var(--theme-color-peach)',
      },
      {
        name: 'Sky Accent',
        role: 'Info banners, hover fills, charts, secondary CTA backgrounds, bright interface lift',
        hex: '#8FD3FF',
        oklch: 'oklch(83.74% 0.092 237.74)',
        color: 'var(--theme-color-sky)',
      },
      {
        name: 'Lilac Accent',
        role: 'Illustration moments, campaign cards, badges, and modern contrast details',
        hex: '#D4C1FF',
        oklch: 'oklch(84.76% 0.087 298.57)',
        color: 'var(--theme-color-lilac)',
      },
      {
        name: 'Graphite Neutral',
        role: 'Dense UI chrome, tertiary labels, icons, table rules, and dark neutral structure',
        hex: '#667281',
        oklch: 'oklch(54.74% 0.028 254.07)',
        color: 'var(--theme-color-graphite)',
      },
      {
        name: 'Pearl Neutral',
        role: 'Page backdrops, card fields, empty states, and spacious low-contrast surfaces',
        hex: '#EEF2F7',
        oklch: 'oklch(95.95% 0.008 253.85)',
        color: 'var(--theme-color-pearl)',
      },
    ],
    usageHeading: 'Suggested Website Usage For Hybrid Theme',
    usageItems: [
      ['Primary Navy', 'Use for navigation, page headers, footers, and the main site framework.'],
      ['Coral Accent', 'Use for primary CTAs, alerts, badges, and high-priority interaction moments.'],
      ['Baby Blue', 'Use for soft content blocks, info banners, secondary panels, and lighter emphasis areas.'],
      ['Steel Blue', 'Use for secondary buttons, hover treatments, chart colors, and supporting navigation accents.'],
      ['Mid Grey', 'Use to ground the interface through borders, muted text, cards, and form structure.'],
    ],
  },
  {
    id: 'civic-theme',
    name: 'Civic Theme',
    storyName: 'Civic Theme',
    sectionTitle: 'Civic Theme',
    eyebrow: 'Theme color palette',
    title: 'Civic theme with a cleaner modern edge.',
    description:
      'This palette is designed to feel trustworthy, calm, and service-oriented without falling into the usual dull visual language. It uses a deep civic blue as the anchor, a cooler supporting blue, a fresh mint surface tone, a confident teal accent, and a practical grey for interface structure.',
    heroClassName: 'theme-artifact-hero--government',
    previewClassName: 'theme-artifact-preview--government',
    eyebrowColor: 'var(--theme-color-accent)',
    accentChip: {
      label: 'Public Service',
      background: 'var(--theme-color-mint)',
      color: 'var(--theme-color-primary)',
    },
    previewTitle: 'Clearer, more welcoming government UX',
    previewDescription:
      'Built for service portals, information-heavy pages, and trusted civic interactions where clarity, accessibility, and professionalism matter as much as visual freshness.',
    actions: [
      {
        label: 'Start Service',
        className: 'button-primary',
        style: 'background: var(--theme-color-mint); color: var(--theme-color-primary);',
      },
      { label: 'Learn More', className: 'button-secondary' },
    ],
    colors: {
      primary: '#12395b',
      secondary: '#3e6f8e',
      mint: '#c7e8df',
      accent: '#2f8f83',
      grey: '#7f8d99',
      sky: '#7db7d9',
      amber: '#caa65c',
      'sage-mist': '#dce9e3',
      slate: '#5f6d79',
      fog: '#eef3f6',
      paper: '#f6f8fb',
      ink: '#0f1720',
      shadow: '0 18px 50px rgba(18, 57, 91, 0.16)',
      heroStart: 'rgba(18, 57, 91, 0.98)',
      heroEnd: 'rgba(47, 143, 131, 0.92)',
      glow: 'rgba(47, 143, 131, 0.18)',
    },
    swatches: [
      {
        name: 'Civic Blue',
        role: 'Site header, navigation, page titles, primary trust anchors',
        hex: '#12395B',
        oklch: 'oklch(33.74% 0.066 247.82)',
        color: 'var(--theme-color-primary)',
      },
      {
        name: 'Service Blue',
        role: 'Secondary buttons, content bands, charting, supporting navigation',
        hex: '#3E6F8E',
        oklch: 'oklch(53.46% 0.076 241.94)',
        color: 'var(--theme-color-secondary)',
      },
      {
        name: 'Mint Surface',
        role: 'Information panels, success surfaces, featured service blocks',
        hex: '#C7E8DF',
        oklch: 'oklch(91.00% 0.036 176.42)',
        color: 'var(--theme-color-mint)',
      },
      {
        name: 'Teal Accent',
        role: 'Primary actions, status emphasis, progress indicators, links',
        hex: '#2F8F83',
        oklch: 'oklch(61.68% 0.095 189.14)',
        color: 'var(--theme-color-accent)',
      },
      {
        name: 'Administrative Grey',
        role: 'Borders, tables, muted text, form framing, utility UI',
        hex: '#7F8D99',
        oklch: 'oklch(64.48% 0.016 245.98)',
        color: 'var(--theme-color-grey)',
      },
      {
        name: 'Sky Accent',
        role: 'Charts, notices, help banners, wayfinding highlights, and open interface moments',
        hex: '#7DB7D9',
        oklch: 'oklch(75.20% 0.078 234.95)',
        color: 'var(--theme-color-sky)',
      },
      {
        name: 'Heritage Amber',
        role: 'Priority notices, program highlights, civic badges, and warm supporting action cues',
        hex: '#CAA65C',
        oklch: 'oklch(74.21% 0.102 83.93)',
        color: 'var(--theme-color-amber)',
      },
      {
        name: 'Sage Mist',
        role: 'Service summaries, confirmation panels, approachable section backgrounds, and quiet data cards',
        hex: '#DCE9E3',
        oklch: 'oklch(92.26% 0.016 166.70)',
        color: 'var(--theme-color-sage-mist)',
      },
      {
        name: 'Slate Neutral',
        role: 'Utility navigation, icon systems, dense data views, and stronger neutral scaffolding',
        hex: '#5F6D79',
        oklch: 'oklch(52.74% 0.025 244.13)',
        color: 'var(--theme-color-slate)',
      },
      {
        name: 'Fog Neutral',
        role: 'Page backgrounds, cards, form wells, and generous breathing room across service flows',
        hex: '#EEF3F6',
        oklch: 'oklch(96.12% 0.007 233.64)',
        color: 'var(--theme-color-fog)',
      },
    ],
    usageHeading: 'Suggested Website Usage For Federal Theme',
    usageItems: [
      ['Civic Blue', 'Use for the global shell, agency masthead, service category headers, and trusted navigation zones.'],
      ['Service Blue', 'Use for secondary surfaces, data views, section dividers, and navigational support patterns.'],
      ['Mint Surface', 'Use to soften dense pages with approachable feature panels, notices, and task-oriented content areas.'],
      ['Teal Accent', 'Use for action states, progress indicators, success messaging, and modern interactive emphasis.'],
      ['Administrative Grey', 'Use for gridlines, muted copy, forms, dividers, and neutral layout framing.'],
    ],
  },
];
